### ISSUE TITLE
CloudFormation errors

### ISSUE THREAD

**Issue by Gonzalo933** [stefanjenkner/ec2-gaming-sunshine#177]
Thanks for this repo! it's extremely useful.

Maybe it would be good to update the instructions to mention that by default the CloudFormation stack is going to use a key pair named `ec2-gaming` and if it doesn't exist it won't create the stack.

Additionally, [the default value for MyIP](https://github.com/stefanjenkner/ec2-gaming-sunshine/blob/main/deploy.py#L77) is not a valid CIDR block (it should be `127.0.0.1/XX`)

**Comment by stefanjenkner** [comment]
Thanks a lot for the bug report, @Gonzalo933 ! 

I updated the docs, fixed the problem with the CIDR block and now allow passing a custom key pair name when deploying via CLI. :v:
